### ISSUE TITLE
UITableView的包装可以考虑增加cell identifier不？

### ISSUE THREAD

**Issue by xilin** [carlSQ/FlexBoxLayout#5]
目前的cache完全是按NSIndexPath来的，在复杂列表里感觉不太方便，而且只关注contentView的出发点虽然好，但是需要对现有应用做比较大的侵入改造。

是否可以考虑像 https://github.com/forkingdog/UITableView-FDTemplateLayoutCell 一样做接口设计呢？

**Comment by carlSQ** [comment]
cell 其实就可以当contentview ，但是目前只支持flexbox 布局自动布局，侵入改造是肯定的，之后会支持autolayout，和flexbox布局，也会提供cell 的接口

**Comment by xilin** [comment]
好的，谢谢
